import React from 'react';
import { FileText, Printer, Stethoscope, Clock, AlertCircle } from 'lucide-react';
import './HealthReport.css';

const HealthReport = ({ selectedLanguage }) => {
  return (
    <div className="report-container">
      <div className="report-header">
        <div>
          <h2 className="page-title">Health Summary Report</h2>
          <p className="subtitle">Share this quick summary with your doctor or emergency responder.</p>
        </div>
        <button className="print-btn" onClick={() => window.print()}>
          <Printer size={20} /> Print / Save PDF
        </button>
      </div>

      <div className="report-paper card">
        <div className="report-brand">
          <Stethoscope size={28} color="var(--color-light-blue-600)" />
          <span>Sahaara AI Clinical Summary ({selectedLanguage})</span>
        </div>

        <div className="report-content">
          <div className="report-section">
            <h3><AlertCircle size={20} /> Reported Symptoms</h3>
            <p className="highlight-text">Severe headache, mild fever, slight dizziness, and nausea.</p>
          </div>

          <div className="report-section">
            <h3><Clock size={20} /> Duration</h3>
            <p>Symptoms started approximately <strong>2 hours ago</strong>.</p>
          </div>

          <div className="report-section">
            <h3><Stethoscope size={20} /> AI Triage Assessment</h3>
            <div className="assessment-box">
              <div className="assessment-row">
                <span className="label">Urgency Level:</span>
                <span className="value moderate">Moderate</span>
              </div>
              <div className="assessment-row">
                <span className="label">Possible Condition:</span>
                <span className="value">Migraine or viral onset (AI estimate)</span>
              </div>
              <div className="assessment-row">
                <span className="label">Suggested Action:</span>
                <span className="value">Rest in a dark room, stay hydrated. If nausea worsens or confusion occurs, seek immediate medical care.</span>
              </div>
            </div>
          </div>
        </div>

        <div className="report-footer">
          <p>Generated on {new Date().toLocaleString()}</p>
          <p className="disclaimer-text">Disclaimer: This report is generated by an AI assistant based on user input and is NOT a medical diagnosis.</p>
        </div>
      </div>
    </div>
  );
};

export default HealthReport;
